
///User Registration
POST http://localhost:8080/v1/user HTTP/1.1
Content-Type: application/json

{
    "userid":""
    "firstname":""
    "lastname":""
    "email":""
    "username": "James"
    "password": "6099"
}

####
///User Login
curl -X POST http://localhost:8080/v1/user/login -d 'username=James' -d 'password=6099' HTTP/1.1


########################################################################
########################################################################
########################################################################

/// Add todos
POST http://localhost:8080/v1/todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZXhwIjoxNjgxOTE2OTgxfQ.cP6__t5d2DQ1ChYvKe5ED6o1UxHJL9y7ie6aUeg8yAU
 
 {
  "name": "",
  "description": "",
  "deadline": "",
}
###

#######
///Fetch all todos
GET http://localhost:8080/v1/todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZXhwIjoxNjgxOTEwMjgxfQ.R73P4UycuQC3i39oDuTqejp8P4bjkXImY1bBA2hQbAs

####
///Fetch all todos
GET http://localhost:8080/v1/todos/05e933cd-0b48-4866-bff6-ebad6695494e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZXhwIjoxNjgxOTEyNzE5fQ.1Q5hFRsLqvy9wgwYBH-nLh47hLVmMddyuTiQBWZUjhA

####
//// Update a specific todos

POST http://localhost:8080/v1/todos/05e933cd-0b48-4866-bff6-ebad6695494e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZXhwIjoxNjgxOTEyMDQwfQ.s8oiMMNuGCk7yOEoF9fg2-lbtFdYFTqJQuBzDb0tLVU

 {
  "_id": "05e933cd-0b48-4866-bff6-ebad6695494e",
  "name": "Flask",
  "description": "Basic of Flask",
  "status": "Undone",
  "deadline": "Four Months"
 }


###
POST http://localhost:8080/v1/todos/05e933cd-0b48-4866-bff6-ebad6695494e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZXhwIjoxNjgxOTA1NDA2fQ.GyBxXk42k-AxEc83PbmLTT9FiywVctiKg3D3l-5Bdew

 {
  "name": "DJango",
  "description": "Basic of Django",
  "status": "Undone",
  "deadline": "Four Months"
 }